framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    session:
        handler_id: null
        cookie_secure: auto
        storage_factory_id: session.storage.factory.native
        cookie_samesite: lax
    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
